version: "3.8"
services:
  configserver:
    image: nithin2889/configserver:latest
    #mem_reservation: 700m
    ports:
      - "8071:8071"
    networks:
      - nithin-bank-network

  eurekaserver:
    image: nithin2889/eurekaserver:latest
    ports:
      - "8761:8761"
    networks:
      - nithin-bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8761/

  accounts:
    image: nithin2889/accounts:latest
    #mem_reservation: 700m
    ports:
      - "8081:8081"
    networks:
      - nithin-bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  loans:
    image: nithin2889/loans:latest
    #mem_reservation: 700m
    ports:
      - "8090:8090"
    networks:
      - nithin-bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

  cards:
    image: nithin2889/cards:latest
    #mem_reservation: 700m
    ports:
      - "9000:9000"
    networks:
      - nithin-bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 360s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/

networks:
  nithin-bank-network: